
(defvar *current-font-idx* 0)
(defvar *font-size* 16)
(defconst *fonts-array-base* [
                              "clearlyu pua"
                              "clearlyu"
                              "clean"
                              "fixed"
                              "open look cursor"
                              "open look glyph"
                              "newspaper"
                              "gothic"
                              "mincho"
                              "fangsong ti"
                              "song ti"
                              "fixed"
                              "nil"
                              "clearlyu alternate glyphs"
                              "clearlyu arabic extra"
                              "clearlyu arabic"
                              "clearlyu devanagari"
                              "clearlyu devangari extra"
                              "clearlyu ligature"
                              "clearlyu pua"
                              "clearlyu"
                              "clean"
                              "fixed"
                              "open look cursor"
                              "open look glyph"
                              "bitstream charter"
                              "courier 10 pitch"
                              "fixed"
                              "Noto Sans Mono CJK TC"
                              "monofur for Powerline"
                              "Lato"
                              "Lato"
                              "Century Schoolbook L"
                              "Khmer OS System"
                              "Nakula"
                              "Chandas"
                              "Roboto Mono Thin for Powerline"
                              "Keraleeyam"
                              "IBM 3270 Narrow"
                              "Noto Sans Mono CJK TC"
                              "Meera"
                              "Source Code Pro for Powerline"
                              "Lato"
                              "Meslo LG S DZ for Powerline"
                              "Noto Sans Mono CJK SC"
                              "Tibetan Machine Uni"
                              "Umpush"
                              "IBM 3270 Semi-Narrow"
                              "DejaVu Sans Mono"
                              "Purisa"
                              "Meslo LG L DZ for Powerline"
                              "Mitra Mono"
                              "Meslo LG M DZ for Powerline"
                              "Noto Serif CJK JP"
                              "Noto Serif CJK KR"
                              "Noto Sans CJK SC"
                              "Norasi"
                              "Loma"
                              "Karumbi"
                              "Droid Sans Mono for Powerline"
                              "Liberation Mono for Powerline"
                              "Roboto Mono Light for Powerline"
                              "Noto Mono for Powerline"
                              "URW Palladio L"
                              "Noto Serif CJK SC"
                              "Noto Serif CJK TC"
                              "Likhan"
                              "Fira Mono for Powerline"
                              "Source Code Pro for Powerline"
                              "Padauk Book"
                              "Phetsarath OT"
                              "Sawasdee"
                              "Sahadeva"
                              "Noto Sans CJK TC"
                              "Tlwg Typist"
                              "Tlwg Typewriter"
                              "Noto Sans CJK KR"
                              "Lato"
                              "URW Gothic L"
                              "URW Chancery L"
                              "Ubuntu"
                              "Mukti Narrow"
                              "Noto Sans CJK JP"
                              "Noto Sans CJK SC"
                              "Meslo LG S for Powerline"
                              "Chilanka"
                              "FreeSerif"
                              "Padauk"
                              "AnjaliOldLipi"
                              "DejaVu Sans Mono for Powerline"
                              "Ubuntu Condensed"
                              "Space Mono for Powerline"
                              "DejaVu Sans"
                              "Source Code Pro for Powerline"
                              "Kinnari"
                              "NovaMono for Powerline"
                              "padmaa"
                              "Tlwg Mono"
                              "Source Code Pro for Powerline"
                              "aakar"
                              "Bitstream Charter"
                              "Space Mono"
                              "Symbol Neu for Powerline"
                              "Hack"
                              "Droid Sans Mono Slashed for Powerline"
                              "Khmer OS"
                              "Courier 10 Pitch"
                              "Inconsolata-g for Powerline"
                              "Lato"
                              "Inconsolata for Powerline"
                              "Laksaman"
                              "Liberation Sans Narrow"
                              "Liberation Mono"
                              "Nimbus Sans L"
                              "Roboto Mono Medium for Powerline"
                              "Manjari"
                              "Noto Sans CJK TC"
                              "Rachana"
                              "Pagul"
                              "Lohit Telugu"
                              "Samanata"
                              "Roboto Mono for Powerline"
                              "Kalimati"
                              "padmaa"
                              "Lato"
                              "Terminess Powerline"
                              "Nimbus Mono L"
                              "Liberation Serif"
                              "Manjari"
                              "Ani"
                              "Lato"
                              "Meslo LG M for Powerline"
                              "Noto Sans Mono CJK SC"
                              "Nimbus Roman No9 L"
                              "Ubuntu"
                              "Cousine for Powerline"
                              "IBM 3270"
                              "Anonymous Pro for Powerline"
                              "Liberation Sans"
                              "Meslo LG L for Powerline"
                              "Manjari"
                              "FreeSans"
                              "Noto Sans Mono CJK JP"
                              "Arimo for Powerline"
                              "Sarai"
                              "Lohit Devanagari"
                              "Noto Color Emoji"
                              "Uroob"
                              "Source Code Pro for Powerline"
                              "Noto Mono"
                              "Dyuthi"
                              "Tlwg Typo"
                              "Droid Sans Mono Dotted for Powerline"
                              "Noto Sans CJK JP"
                              "Lato"
                              "Suruma"
                              "Abyssinica SIL"
                              "Jamrul"
                              "Noto Sans Mono CJK KR"
                              "Waree"
                              "Gargi"
                              "Mukti Narrow"
                              "Inconsolata-dz for Powerline"
                              "DejaVu Serif"
                              "Noto Sans CJK KR"
                              "Noto Sans Mono CJK KR"
                              "Source Code Pro for Powerline"
                              "Garuda"
                              "Rekha"
                              "Ubuntu Mono derivative Powerline"
                              "Tinos for Powerline"
                              "Go Mono for Powerline"
                              "FreeMono"
                              "Ubuntu Mono"
                              "ProFont for Powerline"
                              "URW Bookman L"
                              "Noto Sans Mono CJK JP"
                              ])

(defconst *fonts-array* (map 'array (lambda (a) (format "%s %d" a *font-size*)) *fonts-array-base*))



(defun font-forward ()
  (interactive)
  (setq *current-font-idx* (mod (1+  *current-font-idx*) (length *fonts-array*)))
  (let ((font-to-use (aref *fonts-array* *current-font-idx*)))
    (set-frame-font font-to-use)
    (message "Using font: %s" font-to-use)))

(defun font-backward ()
  (interactive)
  (setq *current-font-idx* (mod (1-  *current-font-idx*) (length *fonts-array*)))
  (let ((font-to-use (aref *fonts-array* *current-font-idx*)))
    (set-frame-font font-to-use)
    (message "Using font: %s" font-to-use)))

(progn
  (global-set-key (kbd "C-=") 'font-forward)
  (global-set-key (kbd "C--") 'font-backward))

