;;; This is an autogenerated file.
;;; Any modifications to this file will probably be lost.
(setq my-packman-packages-list '(utop exec-path-from-shell kotlin-mode ensime scala-mode php-mode d-mode flymake-cursor flymake-haskell-multi flycheck-haskell haskell-mode racer rust-mode unicode-fonts evil-numbers ruby-end bison-mode go-mode flycheck-irony company-irony irony yasnippet rainbow-delimiters paredit magit evil autopair auto-complete))
