;;; This is an autogenerated file.
;;; Any modifications to this file will probably be lost.
(setq my-packman-packages-list '(helm-ag helm aggressive-indent exec-path-from-shell unicode-fonts evil-numbers rainbow-delimiters paredit evil undo-tree autopair auto-complete))
